services:
  - type: web
    name: ems-ocr-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEEPSEEK_OCR_SPACE
        value: khang119966/DeepSeek-OCR-DEMO
    plan: free
