services:
  - type: web
    name: ems-ocr-api
    runtime: python
    rootDir: api
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OCR_LANGS
        value: pt
    plan: free
